[pytest]
asyncio_mode = auto
testpaths = tests
addopts = -v --tb=short

[coverage:run]
source = app
omit =
    app/db/migrations/*
    app/alembic/*

[coverage:report]
show_missing = true
skip_covered = false
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
    raise NotImplementedError
